name = "terminal-dolch"
license = "MIT"
licenselink = "https://github.com/wale/hugo-theme-terminal/blob/master/LICENSE.md"
description = "A simple, retro theme for Hugo. Forked from panr/hugo-theme-terminal to change the colour scheme."
homepage = "https://github.com/wale/hugo-theme-terminal/"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "minimal", "monotone", "multilingual", "personal", "responsive", "simple", "technical", "retro"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.74

[author]
  name = "wale"
  homepage = "https://wale.id.au"
  twitter = "https://twitter.com/spellsaidwrong"
